from chi_pol import *
import matplotlib.pyplot as plt

print("Simulating zero bias field (E0 = 0.0) ...")
omegas_main = np.linspace(0, 4.5, 300)
re_chi_0, im_chi_0 = calc_chi_real_imag(0.0, omegas_main)

print("Simulating bias field (E0 = 0.05) ...")
re_chi_5, im_chi_5 = calc_chi_real_imag(0.05, omegas_main)

print("Simulating bias field (E0 = 0.03) for inset comparison ...")
omegas_inset = np.linspace(1.2, 2.2, 150)
_, im_chi_5_inset = calc_chi_real_imag(0.05, omegas_inset)
_, im_chi_3_inset = calc_chi_real_imag(0.03, omegas_inset)

print("Simulation done.")

plt.figure(figsize=(8, 6))
plt.plot(omegas_main, re_chi_0, 'k--', linewidth=1.5, label=r'$\mathcal{E}_0 = 0.0$')
plt.plot(omegas_main, re_chi_5, 'b-', linewidth=1.2, label=r'$\mathcal{E}_0 = 0.05$')
plt.xlabel('Energy', fontsize=16)
plt.ylabel(r'Re $\chi(\omega)$', fontsize=16)
plt.xlim(0, 4.5)
plt.ylim(-2, 7)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.legend(loc='upper right', fontsize=14)
plt.tick_params(direction='in', top=True, right=True)
plt.tight_layout()
plt.savefig('figs/prb69fig6a.png', dpi=300)
plt.show()
print("Real part of susceptibility is plotted.")

plt.figure(figsize=(8, 6))
plt.plot(omegas_main, im_chi_0, 'k--', linewidth=1.5, label=r'$\mathcal{E}_0 = 0.0$')
plt.plot(omegas_main, im_chi_5, 'b-', linewidth=1.2, label=r'$\mathcal{E}_0 = 0.05$')
plt.xlabel('Energy', fontsize=16)
plt.ylabel(r'Im $\chi(\omega)$', fontsize=16)
plt.xlim(0, 4.5)
plt.ylim(0, 7.5)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.legend(loc='upper right', fontsize=14)
plt.tick_params(direction='in', top=True, right=True)
plt.tight_layout()
plt.savefig('figs/prb69fig6b.png', dpi=300)
plt.show()
print("Imaginary part of susceptibility is plotted.")

plt.figure(figsize=(8, 6))
plt.plot(omegas_inset, im_chi_5_inset, 'b-', linewidth=1.5, label=r'$\mathcal{E}_0 = 0.05$')
plt.plot(omegas_inset, im_chi_3_inset, 'k--', linewidth=1.5, label=r'$\mathcal{E}_0 = 0.03$')
plt.xlabel('Energy', fontsize=16)
plt.ylabel(r'Im $\chi(\omega)$', fontsize=16)
plt.xlim(1.3, 1.8)
plt.ylim(0, 4.5)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.legend(loc='upper right', fontsize=14)
plt.tick_params(direction='in', top=True, right=True)
plt.tight_layout()
plt.savefig('figs/prb69fig6c.png', dpi=300)
plt.show()
print('Franz-Keldysh oscillations is plotted.')

