from pol_alpha import *
import matplotlib.pyplot as plt

print("Simulating for 200 k-points...")
t1, P_dyn_200 = calc_dyn_pol_alpha(T=80, t_max=200, N_k=200)
_, P_ad_200 = calc_ad_pol_alpha(T=80, t_max=200, N_k=200)
print("Simulating for 100 k-points...")
_, P_dyn_100 = calc_dyn_pol_alpha(T=80, t_max=200, N_k=100)
print('Simulation done.')

plt.figure(figsize=(8, 5))
plt.plot(t1, P_dyn_200, '-', lw=1, label='Dynamic')
plt.plot(t1, P_ad_200, '--', lw=1, label='Adiabatic')
plt.xlabel('Time', fontsize=12)
plt.ylabel('Polarization', fontsize=12)
plt.xlim(0, 200)
plt.ylim(0, 1.05)
plt.xticks(fontsize=10)
plt.yticks([0, 0.5, 1.0], fontsize=10)
plt.legend(loc='upper left', fontsize=10, frameon=True)
plt.tick_params(direction='in', top=True, right=True)
plt.tight_layout()
plt.savefig('figs/prb69fig2a.png', dpi=300)
plt.show()
print("Polarization evolution is plotted.")

plt.figure(figsize=(8, 5))
mask = (t1 >= 70) & (t1 <= 150)
plt.plot(t1[mask], P_dyn_200[mask], '-', label='Dynamic (200 k points)')
plt.plot(t1[mask], P_dyn_100[mask], '.', color='gray', ms=5, label='Dynamic (100 k points)')
plt.plot(t1[mask], P_ad_200[mask], '--', label='Adiabatic')
plt.xlabel('Time', fontsize=12)
plt.ylabel('Polarization', fontsize=12)
plt.xlim(70, 150)
plt.ylim(0.992, 1.004)
plt.xticks([80, 120], fontsize=10)
plt.yticks([0.992, 0.996, 1.000], fontsize=10)
plt.legend(loc='lower right', fontsize=10, frameon=True)
plt.tick_params(direction='in', top=True, right=True)
plt.tight_layout()
plt.savefig('figs/prb69fig2b.png', dpi=300)
plt.show()
print("Remnant quantum beats (zoomed-in) is plotted.")
